#!/usr/bin/env bash
# Revalidate scheduler capacity before choosing the NOAUG_* overrides.
# Optional argument: the ID of an already COMPLETED, matching preflight job.
set -euo pipefail
router_root=/gpfs/work/cpt/jiachenhou23/MSE-Router
revision="$router_root/revisions/no_augmentation_v1"
output_root="$router_root/outputs/qwen-mosei-router-v2-no-augmentation"
train_partition="${NOAUG_TRAIN_PARTITION:-gpu4090}"
train_qos="${NOAUG_TRAIN_QOS:-8gpus}"
preflight_partition="${NOAUG_PREFLIGHT_PARTITION:-gpu4090}"
preflight_qos="${NOAUG_PREFLIGHT_QOS:-gpudebug}"
preflight_job="${1:-}"
if [[ -n "$preflight_job" ]]; then
  [[ "$preflight_job" =~ ^[0-9]+$ ]] || exit 2
  state=$(sacct -X -j "$preflight_job" -n -P --format=State)
  [[ "$state" == COMPLETED ]] || { printf 'Preflight is not COMPLETED: %s\n' "$state" >&2; exit 2; }
  jq -e '.status == "ok" and .training_augmentation.mode == "none"' \
    "$output_root/preflight/result.json" >/dev/null
fi
mkdir -p "$output_root/slurm"
# Atomic reservation prevents a repeated invocation from submitting duplicates.
mkdir "$output_root/submission"
record_dir="$output_root/submission"
cd "$revision"
if [[ -z "$preflight_job" ]]; then
  preflight_job=$(sbatch --parsable --partition="$preflight_partition" --qos="$preflight_qos" \
    --job-name=qwen-noaug-preflight --time=01:00:00 \
    --output="$output_root/slurm/%x-%j.out" --error="$output_root/slurm/%x-%j.err" \
    scripts/qwen_noaug.slurm preflight)
  preflight_job="${preflight_job%%;*}"
fi
printf '%s\n' "$preflight_job" | tee "$record_dir/preflight.jobid"
first_job=$(sbatch --parsable --partition="$train_partition" --qos="$train_qos" \
  --dependency="afterok:$preflight_job" --array=0 scripts/qwen_noaug.slurm train)
first_job="${first_job%%;*}"
printf '%s\n' "$first_job" | tee "$record_dir/seed_1111.jobid"
remaining_job=$(sbatch --parsable --partition="$train_partition" --qos="$train_qos" \
  --dependency="afterok:$preflight_job" --array=1-2%2 scripts/qwen_noaug.slurm train)
remaining_job="${remaining_job%%;*}"
printf '%s\n' "$remaining_job" | tee "$record_dir/seeds_2222_3333.jobid"
# cpudebug permits only one submitted job for this user. Chain aggregation on
# the last GPU task instead of consuming that slot while cleanup is pending.
# The aggregation helper exits without writing until all three seeds finish.
printf '%s\n' 'Report is generated by the last successful training task.' | tee "$record_dir/aggregation.txt"
